name: build
on:
  push:
    branches: [ master ]
    paths:
      - .github/workflows/gradle.yml
      - deepworld-config
      - api/**
      - gameserver/**
      - shared/**
      - src/**
      - build.gradle
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.5.0
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Set up JDK 8
      uses: actions/setup-java@v3.6.0
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: brainwine
        path: build/distributions/**
        retention-days: 7
